### ISSUE TITLE
Updated masic: check differences between output files

### ISSUE THREAD

**Issue by biodavidjm** [MoTrPAC/motrpac-proteomics-pnnl-prototype#8]
After updating the latest MASIC version, the output from `step00/step00masic.sh` seems to be identical except for a few files (not including a few of them that just differ in date/version):

```
diff masic_output/MoTrPAC_Pilot_TMT_W_S1_01_12Oct17_Elm_AQ-17-09-02_SICstats.txt masic_output_pre/MoTrPAC_Pilot_TMT_W_S1_01_12Oct17_Elm_AQ-17-09-02_SICstats.txt

diff masic_output/MoTrPAC_Pilot_TMT_W_S1_02_12Oct17_Elm_AQ-17-09-02_SICstats.txt masic_output_pre/MoTrPAC_Pilot_TMT_W_S1_02_12Oct17_Elm_AQ-17-09-02_SICstats.txt
```

However, when looking at the `diff` output, they still seem identical. There might be some extra tab or special character or something that makes the difference. @alchemistmatt , would you mind to confirm?

- `masic_output_pre` folder: previous version output
- `masic_output`folder: new masic version output 

(Same folders/files are affected in the `test_phospho` folder)

**Comment by alchemistmatt** [comment]
Why do you expect the MASIC output to change?  I believe the update to MASIC was to add support for 16-plex TMT (aka TMT Pro)
